Added codable models for Assignment
Slugbotics/Sluggo-iOS pull request #2
Opened 2021-04-16 01:37 UTC by agavgavi

Created Codable models for User, Token, Member, and Team. For now, the JSON decoder is stored in the ViewController but will be moved to manager classes. (It is only there to make sure that we have the decoder's date set to the proper format).

2021-04-18 23:31 UTC, wtpisaac requested changes
I believe the JSON decoding logic can be stored within the classes, and these can be bound to an optional initializer. I will attempt to make these changes.

2021-04-19 00:56 UTC, tdimhcsleumas commented on Sluggo/Models/User.swift
> +        self.init(id: userRecord.id, email: userRecord.email, first_name: userRecord.first_name, last_name: userRecord.last_name, username: userRecord.username)
what's userRecord's type? You could probably abstract most of the json decoding to a base class and then define the initializer to build from a json object

2021-04-19 05:26 UTC, tdimhcsleumas commented on Sluggo/Models/Member.swift
> +          return memberRecord
Good work! :ship:

2021-04-19 05:26 UTC, tdimhcsleumas approved these changes

2021-04-19 05:27 UTC, tdimhcsleumas commented
Good work! :ship:

2021-04-19 15:25 UTC, merged