README Refactor
Slugbotics/Sluggo-iOS pull request #34
Opened 2021-05-30 01:51 UTC by agavgavi

Here is a sample README with installation instructions, feel free to criticize or try running it and let me know if I left anything out.

2021-05-30 04:48 UTC, wtpisaac approved these changes

2021-05-30 04:50 UTC, wtpisaac requested changes
Add instructions for creating normal Users

2021-05-31 06:10 UTC, wtpisaac requested changes
iOS app looks good, although please address the issue in Admin Roles (I discovered that independently of reviewing other components)

I'd like some additional work on the README, which you can see with my review comments.

2021-05-31 06:35 UTC, agavgavi commented on README.md
> +*Note: If you are using the SPA, the login process is simpler*
complete!

2021-05-31 06:35 UTC, agavgavi commented on README.md
> +## Creating Users
adjusted

2021-05-31 06:35 UTC, agavgavi commented on README.md
> +*Note: Once the app is placed on the App Store, the installation process is much simpler*
fixed

2021-05-31 06:35 UTC, agavgavi commented on README.md
> +Sluggo is an open source Issue Tracker for companies, teams, and more. The software is selfhosted, and decentralized in a way that any team can spin up their own instance in minutes! The program star
rewritten

2021-05-31 06:35 UTC, agavgavi commented on README.md
> +## SwiftLint
can do!

2021-06-01 02:59 UTC, wtpisaac approved these changes

2021-06-01 03:00 UTC, tebertt approved these changes
Looks good and reads well

2021-06-01 03:35 UTC, merged